use_gpu: True
device: 0
early_stop:
  patience: 10
federate:
  method: local
  mode: standalone
  total_round_num: 1000
  client_num: 226 #TODO:It is not good to directly specify the number of clients here
data:
  root: data/
  type: shakespeare
  subsample: 0.2
  splits: [0.6,0.2,0.2]
model:
  type: lstm
  in_channels: 80
  out_channels: 80
  embed_size: 8
  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.8
    weight_decay: 0.0
criterion:
  type: character_loss
trainer:
  type: nlptrainer
eval:
  freq: 10
  metrics: ['acc', 'correct']
result_floder: model_heterogeneity/result/nlp
