use_gpu: True
device: 0
early_stop:
  patience: 50
seed: 0
federate:
  method: local
  mode: standalone
  client_num: 5
  total_round_num: 200
  sample_client_rate: 1.0
  make_global_eval: False
data:
  root: data/
  type: femnist
  splits: [ 0.6,0.2,0.2 ]
  transform: [ [ 'ToTensor' ], [ 'Normalize', { 'mean': [ 0.9637 ], 'std': [ 0.1592 ] } ] ]
dataloader:
  batch_size: 256
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 1e-4
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 1
  metrics: [ 'acc']
  report: [ 'weighted_avg', 'avg', 'raw' ]
  best_res_update_round_wise_key: test_acc
exp_name: local_femnist_5_client_low