use_gpu: True
device: 0
early_stop:
  patience: 15
seed: 0 #[0,1,2]
federate:
  mode: standalone
  method: fedhenn
  client_num: 5
  total_round_num: 200
  sample_client_rate: 1.0
  make_global_eval: False
data:
  root: data/
  local_eval_whole_test_dataset: True #important! Whether the test dataset for each client is equivalent to the test dataset for the unsplit dataset
  type: 'CIFAR10@torchvision'
  splits: [1.0, 0.0, 0.0]
  num_workers: 0
  transform: [['ToTensor'], ['Normalize', {'mean': [0.4914, 0.4822, 0.4465], 'std': [0.2470, 0.2435, 0.2616]}]] #very import
  test_transform: [['ToTensor'], ['Normalize', {'mean': [0.4914, 0.4822, 0.4465], 'std': [0.2470, 0.2435, 0.2616]}]]
  args: [{'download': True}]
  splitter: 'lda'
  splitter_args: [{'alpha': 1.0}] #[100,1.0,0.1]
dataloader:
  batch_size: 256
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 1e-4
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedhenn_trainer
grad:
  grad_clip: 5.0
eval:
  freq: 1
  metrics: ['acc', 'correct']
  report : ['weighted_avg', 'avg', 'raw']
  best_res_update_round_wise_key: test_acc
exp_name: 'FedHeNN_5_clients_on_cifa10_low_heterogeneity_alpha_1.0'
