use_gpu: True
device: 0
early_stop:
  patience: 50
seed: 0
check_completeness: False
federate:
  mode: standalone
  method: fedpcl
  client_num: 5
  total_round_num: 200
  sample_client_rate: 1.0
  make_global_eval: False
data:
  root: data/
  local_eval_whole_test_dataset: True #important! Whether the test dataset for each client is equivalent to the test dataset for the unsplit dataset
  type: 'CIFAR10@torchvision'
  splits: [1.0, 0.0, 0.0]
  transform: [['ToTensor'], ['Normalize', {'mean': [0.4914, 0.4822, 0.4465], 'std': [0.2470, 0.2435, 0.2616]}]]
  test_transform: [['ToTensor'], ['Normalize', {'mean': [0.4914, 0.4822, 0.4465], 'std': [0.2470, 0.2435, 0.2616]}]]
  args: [{'download': True}]
  splitter: 'lda'
  splitter_args: [{'alpha': 100.0}]
dataloader:
  batch_size: 256
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 1e-4
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedpcl_cv_trainer
grad:
  grad_clip: 10.0
model:
  type: CNN_3layers_proto
  out_channels: 10
  dropout: 0.
  hidden: 256
  filter_channels: [128,64,64]
eval:
  freq: 1
  metrics: ['acc']
  report : ['weighted_avg', 'avg']
  best_res_update_round_wise_key: test_acc
exp_name: 'FedPCL_5_clients_on_cifa10_low_heterogeneity'
