use_gpu: True
device: 0
early_stop:
  patience: 10
seed: 12345
federate:
  method: fccl
  mode: standalone
  total_round_num: 40
  sample_client_rate: 1.0
  client_num: 4
  make_global_eval: False
MHFL:
  task: CV
  public_dataset: Cifar100
  public_path: ./data
  public_train:
    batch_size: 256
    epochs: 50
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.0
data:
  root: ./data/
  type: officehome
  splits: [ 0.6,0.2,0.2 ]
  transform: [ [ 'ToTensor' ], [ 'Normalize', { 'mean': [ 0.9637 ], 'std': [ 0.1592 ] } ] ]
dataloader:
  batch_size: 256
train:
  local_update_steps: 10
  batch_or_epoch: epoch
  optimizer:
    lr: 0.001
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: fccl_trainer
eval:
  freq: 1
  metrics: ['top5', 'acc', 'correct']
  best_res_update_round_wise_key: test_loss
fccl:
  structure: homogeneity
  beta: 0.1
  off_diag_weight: 0.0051
  pretrain_epoch: 1
  pretrain_path: 'officehome'
  loss_dual_weight: 1