client_1:
  model:
    out_channels: 65
    type: resnet18
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 10
    batch_or_epoch: epoch
    optimizer:
      type: Adam
      lr: 0.01
      weight_decay: 0.0
client_2:
  model:
    out_channels: 65
    type: resnet34
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 10
    batch_or_epoch: epoch
    optimizer:
      type: Adam
      lr: 0.01
      weight_decay: 0.0
client_3:
  model:
    out_channels: 65
    type: googlenet
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 10
    batch_or_epoch: epoch
    optimizer:
      type: Adam
      lr: 0.01
      weight_decay: 0.0
client_4:
  model:
    out_channels: 65
    type: resnet12
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 10
    batch_or_epoch: epoch
    optimizer:
      type: Adam
      lr: 0.01
      weight_decay: 0.0